services:
  backend:
    networks:
      loanhub:
      public_edge:
        aliases:
          - loanhub-api

  frontend:
    networks:
      loanhub:
      public_edge:
        aliases:
          - loanhub-web

networks:
  public_edge:
    external: true
    name: public-edge
